### PR TITLE
Adding dask-gateway compatible image

### PR DESCRIPTION
**Pull request by mapsacosta**
This PR includes a new separate folder for a coffea-dask image compatible with dask-gateway API servers running on upstream Dask DockerHub images and Helm charts.

### CODE REVIEW

**Comment by oshadura** [comment]
@mapsacosta thanks a lot for contribution! Do you know when is planned updates on gateway side to change requirements (dask==2.30.0)?

**Review by oshadura — COMMENTED** [review]
I think you wanted to _base_ image on `coffea-dask-cc7` and not `coffea-dask` (Debian) :)
Other ideas is maybe to _base_ image on `coffea-base-cc7:0.7.7-fastjet-3.3.4.0rc9` then we will be able to:
- [ ] Add separate file for dispatch GH workflow to update/rebuild image each time `coffea-base-cc7`  is tagged (e.g. new version of coffea): https://github.com/CoffeaTeam/docker-coffea-dask/blob/main/.github/workflows/repo_dispatch.yml
- [ ] Add image in list of images to be tested GH CI and CD workflows: https://github.com/CoffeaTeam/docker-coffea-dask/blob/main/.github/workflows/gh-cd.yml and https://github.com/CoffeaTeam/docker-coffea-dask/blob/main/.github/workflows/gh-cd.yml
 
It will require to add some missing packages such as `htcondor` but also give you more flexibility:  https://github.com/CoffeaTeam/docker-coffea-dask/blob/main/dask-cc7/Dockerfile#L13-L18

Let me know what do you think?

**Comment by mapsacosta** [comment]
I actually just stumbled upon this [Dockerfile](https://github.com/dask/dask-gateway/blob/882c628a2f9f51a62e35ff737c716ce8714d5dea/dask-gateway/Dockerfile#L55) in the dask-gateway repository. They are pretty much up to date with Dask releases (a month?). So this indicates that maybe the only pinned version should be dask-gateway==0.9.0 and then the only thing we should worry about is having sufficiently new versions of `dask` and `distributed` that match: this image, our EAF notebook image and some custom dask-gateway and dask-gateway-server images I will build for the EAF.

In the long run, this will probably be good esp since we're actively doing development for upstream dask-gateway integration with [HTCondor](https://github.com/dask/dask-gateway/issues/440). I'll get a repo set up for that in a bit.

Perhaps we can trigger a [cross-repo](https://blog.marcnuri.com/triggering-github-actions-across-different-repositories#triggering-events-across-repository-workflows) action that keeps at least a **fixed** list of packages in sync? this could be useful also if other institutions want to build on top of us. Just a suggestion but let me know if this sounds good and I'll get something working by the end of the day 👍

**Comment by mapsacosta** [comment]
@oshadura In the meantime, I also applied your suggested fix about changing the base, so that should be good to go too

**Comment by mapsacosta** [comment]
> [...] this indicates that maybe the only pinned version should be dask-gateway==0.9.0 and then the only thing we should worry about is having sufficiently new versions of `dask` and `distributed` that match: this image, our EAF notebook image and some custom dask-gateway and dask-gateway-server images I will build for the EAF.

This is done! I built and pushed "EAF dask-gateway-server" images which are for now just exact copies of upstream. See [GitHub actions run](https://github.com/mapsacosta/EAFJupyter/actions/runs/1214393221) and [build context](https://github.com/mapsacosta/EAFJupyter/tree/master/dask-gateway)t for the pipeline.

> In the long run, this will probably be good esp since we're actively doing development for upstream dask-gateway integration with [HTCondor](https://github.com/dask/dask-gateway/issues/440). I'll get a repo set up for that in a bit.

No need, I just re-used the main EAFJupyter repo and created a subfolder: `EAFJupyter/dask-gateway`

> Perhaps we can trigger a [cross-repo](https://blog.marcnuri.com/triggering-github-actions-across-different-repositories#triggering-events-across-repository-workflows) action that keeps at least a **fixed** list of packages in sync? this could be useful also if other institutions want to build on top of us. Just a suggestion but let me know if this sounds good 
> and I'll get something working by the end of the day 👍

This will be easier now that we have control of all versions in dask-gateway and dask-gateway-server images. thoughts? @oshadura

**Comment by mapsacosta** [comment]
Awesome! Thanks @oshadura Do you know what's the image name/tag?

**Comment by oshadura** [comment]
@mapsacosta I added GH Actions CD workflow for this image just now, but as soon as @nsmith- will create image coffeateam/coffea-dask-cc7-gateway in Dockerhub I will let you know tag.

**Comment by oshadura** [comment]
@mapsacosta see image in https://hub.docker.com/repository/docker/coffeateam/coffea-dask-cc7-gateway

**Pull request merged**
