### PR TITLE
Pin htcondor to 9.2.0

### PR DESCRIPTION
**Pull request by lgray**
Issue with htcondor at lpc, pin to 9.2.0 python bindings for now.

### CODE REVIEW

**Comment by oshadura** [comment]
@lgray could you please elaborate a bit more what is a problem you see?

**Comment by lgray** [comment]
This is an FNAL specific thing. The scripts for using multiple schedds (which using condor 9.0.1) at the lpc depend on implementation details which break in 9.3.0 as compared to 9.2.0.

**Comment by oshadura** [comment]
Let's make somewhere note/open issue, so we will not forget why it was pinned?

**Comment by lgray** [comment]
Yes, good idea!

**Comment by lgray** [comment]
@mapsacosta FYI

**Comment by nsmith-** [comment]
FWIW lpcjobqueue has a copy of the schedd-selecting script internally, in https://github.com/CoffeaTeam/lpcjobqueue/blob/main/src/lpcjobqueue/schedd.py#L11 
Perhaps it will need updating along with the LPC-wide one at some point?

**Pull request merged**
